set rs_root [file normalize [file join [file dirname [info script]] ..]]
set alexnet_root [file join $rs_root .. alexnet]
set rs_sources [list]
lappend rs_sources [file join $rs_root rtl packed_mac/alexnet_row_stationary_pe.sv]
lappend rs_sources [file join $rs_root rtl packed_mac/alexnet_rs_filter_row_rf.sv]
lappend rs_sources [file join $rs_root rtl sa/alexnet_sa_m8r128_row_stationary.sv]
lappend rs_sources [file join $alexnet_root rtl postprocess/alexnet_n8_requant.sv]
lappend rs_sources [file join $alexnet_root rtl postprocess/alexnet_m8n8_parallel_requant.sv]
lappend rs_sources [file join $alexnet_root rtl postprocess/alexnet_m8n8_requant_serializer.sv]
lappend rs_sources [file join $alexnet_root rtl result/alexnet_n8_output_router.sv]
lappend rs_sources [file join $rs_root rtl control/alexnet_row_stationary_graph_scheduler.sv]
lappend rs_sources [file join $rs_root rtl integration/alexnet_m8r128_row_stationary_core.sv]
lappend rs_sources [file join $rs_root rtl integration/alexnet_row_stationary_graph_engine.sv]
lappend rs_sources [file join $alexnet_root rtl memory/alexnet_m16_patch_pingpong.sv]
lappend rs_sources [file join $alexnet_root rtl memory/alexnet_n8_activation_bank.sv]
lappend rs_sources [file join $alexnet_root rtl memory/alexnet_n8_activation_pingpong.sv]
lappend rs_sources [file join $alexnet_root rtl memory/alexnet_m8n8_int32_partial_sum_bank.sv]
lappend rs_sources [file join $rs_root rtl memory/alexnet_row_stationary_psum_scratch.sv]
lappend rs_sources [file join $rs_root rtl dma/alexnet_row_stationary_weight_dma_bridge.sv]
lappend rs_sources [file join $rs_root rtl integration/alexnet_row_stationary_banked_engine.sv]
lappend rs_sources [file join $rs_root rtl feeder/alexnet_row_stationary_gather.sv]
lappend rs_sources [file join $alexnet_root rtl dma/alexnet_parameter_record_loader.sv]
lappend rs_sources [file join $alexnet_root rtl dma/alexnet_axis128_to_n8_unpacker.sv]
lappend rs_sources [file join $alexnet_root rtl dma/alexnet_n8_to_axis128_packer.sv]
lappend rs_sources [file join $alexnet_root rtl pool/alexnet_n8_maxpool3x3.sv]
lappend rs_sources [file join $alexnet_root rtl integration/alexnet_conv_result_pool_service.sv]
lappend rs_sources [file join $alexnet_root rtl integration/alexnet_m8n126_inplace_pool_service.sv]
lappend rs_sources [file join $rs_root rtl integration/alexnet_row_stationary_ddr_engine.sv]
lappend rs_sources [file join $rs_root rtl integration alexnet_row_stationary_accelerator_top.sv]
lappend rs_sources [file join $alexnet_root rtl control alexnet_axi_lite_regs.sv]
lappend rs_sources [file join $alexnet_root .. rtl axi_dma_simple_master.sv]
