#ifndef ALEXNET_BUFFER_LAYOUT_H
#define ALEXNET_BUFFER_LAYOUT_H

#define ALEXNET_BASE_ALIGNMENT          128u
#define ALEXNET_DMA_ALIGNMENT             8u

#define ALEXNET_CAMERA_WIDTH             224u
#define ALEXNET_CAMERA_HEIGHT            224u
#define ALEXNET_CAMERA_PIXEL_STRIDE         8u
#define ALEXNET_CAMERA_BUFFER_BYTES     401408u
#define ALEXNET_CAMERA_N8_LANE_MASK       0x07u

#define ALEXNET_ACTIVATION_A_BYTES       64896u
#define ALEXNET_ACTIVATION_B_BYTES       43264u
#define ALEXNET_WEIGHT_BYTES          61123264u
#define ALEXNET_PARAMETER_BYTES         165504u
#define ALEXNET_OUTPUT_VALID_BYTES        1000u
#define ALEXNET_OUTPUT_ALLOC_BYTES        1024u

/* One coherent DDR allocation; every programmed base is 128-byte aligned. */
#define ALEXNET_BUFFER_INPUT_OFFSET           0u
#define ALEXNET_BUFFER_ACT_A_OFFSET      401408u
#define ALEXNET_BUFFER_ACT_B_OFFSET      466304u
#define ALEXNET_BUFFER_WEIGHTS_OFFSET    509568u
#define ALEXNET_BUFFER_PARAMETERS_OFFSET 61632896u
#define ALEXNET_BUFFER_OUTPUT_OFFSET     61798400u
#define ALEXNET_DMA_USED_BYTES           61799424u

#endif
