create_clock -name clk -period 5.000 -waveform {0.000 2.500} [get_ports clk]
set_input_delay -clock clk -min 0.500 [get_ports -filter {DIRECTION == IN && NAME != clk}]
set_input_delay -clock clk -max 1.000 [get_ports -filter {DIRECTION == IN && NAME != clk}]
set_output_delay -clock clk -min 0.500 [all_outputs]
set_output_delay -clock clk -max 1.000 [all_outputs]
