`timescale 1ns/1ps

// One real trained tile from every AlexNet layer.  Vectors are generated by
// alexnet_board_full_graph_golden from the frozen board model.  This keeps the
// simulation to 26,859 K issues while crossing the real M8xN128 SA, packed
// PEs, FC6 continuation accumulator and 64-DSP requant/result path.
module tb_alexnet_m8n128_trained_layer_tiles;
  logic clk = 1'b0;
  logic rst;

  logic command_valid, command_ready;
  logic [3:0] command_layer_id;
  logic command_mode_split_n64;
  logic [7:0] command_bank_enable;
  logic [15:0] command_n_lane_mask [0:7];
  logic [15:0] command_n_base;
  logic [7:0] command_n_count;
  logic [12:0] command_m_base;
  logic [3:0] command_group0_m_count, command_group1_m_count;
  logic [12:0] command_k_count;
  logic command_accum_first, command_accum_final, command_result_enable;
  logic [15:0] command_weight_context_tag, command_patch_context_tag;
  logic [15:0] command_tile_tag;

  logic patch_valid, patch_ready;
  logic signed [7:0] patch_values [0:15];
  logic [11:0] patch_k;
  logic patch_last;
  logic [15:0] patch_m_lane_mask;
  logic [15:0] patch_context_tag;

  logic weight_valid, weight_ready;
  logic signed [7:0] weight_values [0:7][0:15];
  logic [11:0] weight_k;
  logic weight_last;
  logic [7:0] weight_bank_enable;
  logic [15:0] weight_n_lane_mask [0:7];
  logic [15:0] weight_context_tag;

  logic parameter_request_valid, parameter_request_ready;
  logic [3:0] parameter_request_layer_id;
  logic [15:0] parameter_request_n_base;
  logic [15:0] parameter_request_context_tag;
  logic parameter_valid, parameter_ready;
  logic [15:0] parameter_n_base, parameter_context_tag;
  logic signed [31:0] parameter_bias [0:7];
  logic signed [17:0] parameter_multiplier [0:7];
  logic [5:0] parameter_right_shift [0:7];
  logic [7:0] parameter_relu;

  logic result_valid, result_ready;
  logic [63:0] result_values [0:7];
  logic [7:0] result_lane_mask [0:7];
  logic [3:0] result_m_count;
  logic [12:0] result_m_base;
  logic [15:0] result_n_base;
  logic [15:0] result_tile_tag;
  logic result_last_slice;
  logic command_done, command_error, busy, accumulator_open, fault;
  logic [31:0] active_cycles, issue_cycles;
  logic [31:0] patch_stall_cycles, weight_stall_cycles;
  logic [31:0] result_stall_cycles;
  logic [63:0] useful_mac_count, physical_mac_slot_count;

  logic [127:0] patch_memory [0:9215];
  logic [1023:0] weight_memory [0:9215];
  logic [63:0] parameter_memory [0:111];
  logic [7:0] expected_memory [0:1023];
  bit expected_seen [0:1023];

  string vector_root;
  int active_layer;
  int active_m_count;
  int active_n_count;
  int result_bytes_checked;
  int result_last_checked;
  int total_result_bytes;
  longint unsigned watchdog_cycles;

  alexnet_m8n128_tile_payload #(
      .PIPE_FLUSH_CYCLES(32)
  ) dut (.*);

  always #2.5 clk = ~clk;

  always_comb begin
    parameter_request_ready = 1'b1;
    parameter_valid = 1'b1;
    parameter_n_base = parameter_request_n_base;
    parameter_context_tag = parameter_request_context_tag;
    parameter_relu = 0;
    for (int lane = 0; lane < 8; lane++) begin
      parameter_bias[lane] =
          $signed(parameter_memory[parameter_request_n_base + lane][31:0]);
      parameter_multiplier[lane] =
          $signed(parameter_memory[parameter_request_n_base + lane][49:32]);
      parameter_right_shift[lane] =
          parameter_memory[parameter_request_n_base + lane][55:50];
      parameter_relu[lane] =
          parameter_memory[parameter_request_n_base + lane][56];
    end
  end

  always_ff @(posedge clk) begin
    if (rst) begin
      watchdog_cycles <= 0;
    end else begin
      watchdog_cycles <= watchdog_cycles + 1;
      if (watchdog_cycles != 0 && watchdog_cycles % 4096 == 0) begin
        $display("ALEXNET_TRAINED_PROGRESS cycles=%0d layer=%0d issues=%0d state=%0d",
                 watchdog_cycles, active_layer, issue_cycles, dut.state_q);
        $fflush();
      end
      if (watchdog_cycles >= 100000)
        $fatal(1,
               "trained tile global timeout cycles=%0d layer=%0d issues=%0d state=%0d",
               watchdog_cycles, active_layer, issue_cycles, dut.state_q);
    end
    if (!rst && result_valid && result_ready) begin
      if (result_tile_tag != (16'h7000 | active_layer))
        $fatal(1, "trained tile tag mismatch layer=%0d got=%h",
               active_layer, result_tile_tag);
      for (int row = 0; row < 8; row++) begin
        for (int lane = 0; lane < 8; lane++) begin
          int logical_m;
          int logical_n;
          int expected_index;
          logic [7:0] got;
          logical_m = result_m_base + row;
          logical_n = result_n_base + lane;
          got = result_values[row][lane*8 +: 8];
          if (row < result_m_count && logical_m < active_m_count &&
              logical_n < active_n_count && result_lane_mask[row][lane]) begin
            expected_index = logical_m * active_n_count + logical_n;
            if (got !== expected_memory[expected_index])
              $fatal(1,
                     "trained tile mismatch layer=%0d m=%0d n=%0d got=%0d expected=%0d",
                     active_layer, logical_m, logical_n, $signed(got),
                     $signed(expected_memory[expected_index]));
            if (expected_seen[expected_index])
              $fatal(1, "duplicate trained result layer=%0d m=%0d n=%0d",
                     active_layer, logical_m, logical_n);
            expected_seen[expected_index] = 1'b1;
            result_bytes_checked++;
          end else if (row < result_m_count &&
                       (got != 0 || result_lane_mask[row][lane])) begin
            $fatal(1,
                   "inactive trained result not zero layer=%0d m=%0d n=%0d",
                   active_layer, logical_m, logical_n);
          end
        end
      end
      if (result_last_slice)
        result_last_checked++;
    end
  end

  task automatic load_layer_vectors(input int layer, input int k_total,
                                    input int m_count, input int n_count);
    string path;
    begin
      path = $sformatf("%s/layer%0d/patch.mem", vector_root, layer);
      $readmemh(path, patch_memory, 0, k_total-1);
      path = $sformatf("%s/layer%0d/weight.mem", vector_root, layer);
      $readmemh(path, weight_memory, 0, k_total-1);
      path = $sformatf("%s/layer%0d/parameter.mem", vector_root, layer);
      $readmemh(path, parameter_memory, 0, n_count-1);
      path = $sformatf("%s/layer%0d/expected.mem", vector_root, layer);
      $readmemh(path, expected_memory, 0, m_count*n_count-1);
    end
  endtask

  task automatic configure_descriptor(
      input int layer, input bit split_mode, input int n_count,
      input int m0_count, input int m1_count, input int k_count,
      input bit accum_first, input bit accum_final);
    begin
      command_layer_id = layer;
      command_mode_split_n64 = split_mode;
      command_n_base = 0;
      command_n_count = n_count;
      command_m_base = 0;
      command_group0_m_count = m0_count;
      command_group1_m_count = m1_count;
      command_k_count = k_count;
      command_accum_first = accum_first;
      command_accum_final = accum_final;
      command_result_enable = accum_final;
      command_weight_context_tag = 16'h6000 | layer;
      command_patch_context_tag = 16'h7000 | layer;
      command_tile_tag = 16'h7000 | layer;
      command_bank_enable = 0;
      for (int bank = 0; bank < 8; bank++) begin
        command_n_lane_mask[bank] = 0;
        if (split_mode) begin
          command_bank_enable[bank] = 1'b1;
          for (int lane = 0; lane < 16; lane++)
            command_n_lane_mask[bank][lane] =
                16*(bank % 4) + lane < n_count;
        end else begin
          for (int lane = 0; lane < 16; lane++)
            command_n_lane_mask[bank][lane] = 16*bank + lane < n_count;
          command_bank_enable[bank] = |command_n_lane_mask[bank];
        end
      end
    end
  endtask

  task automatic send_chunk(
      input int layer, input bit split_mode, input int n_count,
      input int m0_count, input int m1_count, input int global_k_offset,
      input int k_count, input bit accum_first, input bit accum_final);
    bit completed;
    begin
      configure_descriptor(layer, split_mode, n_count, m0_count, m1_count,
                           k_count, accum_first, accum_final);
      @(negedge clk);
      command_valid = 1'b1;
      do @(posedge clk); while (!command_ready);
      @(negedge clk);
      command_valid = 1'b0;

      for (int local_k = 0; local_k < k_count; local_k++) begin
        int global_k;
        // Change payload only on the falling edge.  Updating it immediately
        // after a rising-edge handshake creates a simulator scheduling race
        // with the DUT's always_ff sampling of patch_last and the K index.
        @(negedge clk);
        global_k = global_k_offset + local_k;
        for (int lane = 0; lane < 16; lane++)
          patch_values[lane] = patch_memory[global_k][lane*8 +: 8];
        for (int bank = 0; bank < 8; bank++) begin
          weight_n_lane_mask[bank] =
              split_mode && bank >= 4 ? 16'd0 :
              command_n_lane_mask[bank];
          for (int lane = 0; lane < 16; lane++)
            weight_values[bank][lane] =
                weight_memory[global_k][(bank*16+lane)*8 +: 8];
        end
        patch_k = local_k;
        weight_k = local_k;
        patch_last = local_k == k_count-1;
        weight_last = patch_last;
        patch_m_lane_mask = 0;
        for (int lane = 0; lane < 8; lane++) begin
          patch_m_lane_mask[lane] = lane < m0_count;
          patch_m_lane_mask[lane+8] = split_mode && lane < m1_count;
        end
        patch_context_tag = command_patch_context_tag;
        weight_context_tag = command_weight_context_tag;
        weight_bank_enable = split_mode ? 8'h0f : command_bank_enable;

        patch_valid = 1'b1;
        weight_valid = 1'b1;
        do @(posedge clk); while (!(patch_ready && weight_ready));
      end
      @(negedge clk);
      patch_valid = 1'b0;
      weight_valid = 1'b0;
      patch_last = 1'b0;
      weight_last = 1'b0;

      completed = 1'b0;
      for (int timeout = 0; timeout < 12000; timeout++) begin
        @(posedge clk);
        if (command_done) begin
          completed = 1'b1;
          if (command_error || fault)
            $fatal(1, "trained payload failed layer=%0d offset=%0d",
                   layer, global_k_offset);
          break;
        end
      end
      if (!completed)
        $fatal(1, "trained payload timeout layer=%0d offset=%0d state=%0d",
               layer, global_k_offset, dut.state_q);
    end
  endtask

  task automatic run_layer(input int layer);
    bit split_mode;
    int m0_count;
    int m1_count;
    int m_count;
    int n_count;
    int k_total;
    int k_offset;
    int k_count;
    begin
      split_mode = layer <= 2;
      m0_count = layer <= 2 ? 8 : layer <= 5 ? 8 : 1;
      m1_count = layer <= 2 ? 8 : 0;
      m_count = m0_count + m1_count;
      n_count = layer <= 2 ? 64 : layer <= 5 ? 112 : 16;
      case (layer)
        1: k_total = 363;
        2: k_total = 1600;
        3: k_total = 1728;
        4: k_total = 3456;
        5: k_total = 2304;
        6: k_total = 9216;
        7, 8: k_total = 4096;
        default: $fatal(1, "invalid trained layer %0d", layer);
      endcase

      active_layer = layer;
      active_m_count = m_count;
      active_n_count = n_count;
      result_bytes_checked = 0;
      result_last_checked = 0;
      $display("ALEXNET_TRAINED_LAYER_START layer=%0d k=%0d m=%0d n=%0d",
               layer, k_total, m_count, n_count);
      $fflush();
      for (int index = 0; index < 1024; index++)
        expected_seen[index] = 1'b0;
      load_layer_vectors(layer, k_total, m_count, n_count);
      $display("ALEXNET_TRAINED_LAYER_LOADED layer=%0d", layer);
      $fflush();

      k_offset = 0;
      while (k_offset < k_total) begin
        k_count = k_total - k_offset > 4096 ? 4096 : k_total-k_offset;
        send_chunk(layer, split_mode, n_count, m0_count, m1_count,
                   k_offset, k_count, k_offset == 0,
                   k_offset + k_count == k_total);
        k_offset += k_count;
      end

      if (accumulator_open)
        $fatal(1, "trained layer left accumulator open layer=%0d", layer);
      if (result_bytes_checked != m_count*n_count ||
          result_last_checked != 1)
        $fatal(1,
               "trained layer coverage mismatch layer=%0d bytes=%0d/%0d last=%0d",
               layer, result_bytes_checked, m_count*n_count,
               result_last_checked);
      for (int index = 0; index < m_count*n_count; index++)
        if (!expected_seen[index])
          $fatal(1, "trained layer omitted byte layer=%0d index=%0d",
                 layer, index);
      total_result_bytes += result_bytes_checked;
      $display("ALEXNET_TRAINED_LAYER_TILE_PASS layer=%0d k=%0d m=%0d n=%0d bytes=%0d",
               layer, k_total, m_count, n_count, result_bytes_checked);
      $fflush();
    end
  endtask

  initial begin
    if (!$value$plusargs("VECTOR_ROOT=%s", vector_root))
      $fatal(1, "VECTOR_ROOT plusarg is required");
    rst = 1'b1;
    command_valid = 1'b0;
    patch_valid = 1'b0;
    weight_valid = 1'b0;
    result_ready = 1'b1;
    total_result_bytes = 0;
    for (int bank = 0; bank < 8; bank++) begin
      command_n_lane_mask[bank] = 0;
      weight_n_lane_mask[bank] = 0;
      for (int lane = 0; lane < 16; lane++)
        weight_values[bank][lane] = 0;
    end
    for (int lane = 0; lane < 16; lane++)
      patch_values[lane] = 0;

    repeat (8) @(negedge clk);
    rst = 1'b0;
    for (int layer = 1; layer <= 8; layer++)
      run_layer(layer);

    if (issue_cycles != 26859)
      $fatal(1, "trained total issue mismatch got=%0d", issue_cycles);
    if (total_result_bytes != 4784)
      $fatal(1, "trained total result byte mismatch got=%0d",
             total_result_bytes);
    $display("ALEXNET_M8N128_TRAINED_LAYER_TILES_TEST_PASSED layers=8 issues=%0d bytes=%0d active=%0d",
             issue_cycles, total_result_bytes, active_cycles);
    $finish;
  end

endmodule
