`timescale 1ns/1ps

// Full 128-bit DMA input/output boundary around the measured M4xN8 conv2 path.
//
// The MM2S-fed compute child and the N8-to-S2MM result adapter are unchanged.
// Result metadata errors allow the owned S2MM transfer to drain but interlock
// every later chunk launch until software clears the sticky result error.
module alexnet_m4n8_rs_dma_io_activation_resident_weight_dual_accum_datapath #(
    parameter bit EXTERNAL_COMPUTE = 1'b0,
    parameter int SLICE_INDEX = 0,
    parameter int FIFO_DEPTH = 64,
    parameter int MAX_INPUT_WIDTH = 224,
    parameter int WEIGHT_DEPTH = 968,
    parameter int SEGMENT_DEPTH = 512,
    parameter int DIM_W = 8,
    parameter int K_INDEX_W = 10,
    parameter int TILE_TAG_W = 16,
    parameter int TENSOR_TAG_W = 16,
    parameter int WEIGHT_CONTEXT_TAG_W = 16,
    parameter int ACCUM_CONTEXT_TAG_W = 16,
    parameter int CHUNK_INDEX_W = 8,
    parameter int N_BASE_W = 16,
    parameter int DMA_BYTE_COUNT_W = 16,
    parameter int RESULT_MAX_WORDS = 2 * SEGMENT_DEPTH,
    parameter int WEIGHT_COUNT_W = $clog2(WEIGHT_DEPTH + 1),
    parameter int ACTIVATION_COUNT_W = $clog2(2 * SEGMENT_DEPTH + 1),
    parameter int BANK_COUNT_W = $clog2(2 * SEGMENT_DEPTH + 1)
) (
    input logic clk,
    input logic rst,
    input logic ce,

    input  logic cfg_valid,
    output logic cfg_ready,
    input  logic [1:0] cfg_destination,
    input  logic [N_BASE_W-1:0] cfg_n64_tile_base,
    input  logic [2:0] cfg_slice_index,
    input  logic [7:0] cfg_lane_mask,
    input  logic signed [31:0] cfg_bias [0:7],
    input  logic signed [17:0] cfg_multiplier [0:7],
    input  logic [5:0] cfg_right_shift [0:7],
    input  logic [7:0] cfg_relu,

    input  logic dma_clear_error,
    input  logic dma_descriptor_valid,
    output logic dma_descriptor_ready,
    input  logic [1:0] dma_descriptor_destination,
    input  logic [ACTIVATION_COUNT_W-1:0] dma_descriptor_word_count,
    input  logic [DMA_BYTE_COUNT_W-1:0] dma_descriptor_byte_count,
    input  logic [7:0] dma_descriptor_lane_mask,
    input  logic [TENSOR_TAG_W-1:0] dma_descriptor_tag,
    input  logic [127:0] s_axis_tdata,
    input  logic [15:0] s_axis_tkeep,
    input  logic s_axis_tvalid,
    output logic s_axis_tready,
    input  logic s_axis_tlast,

    input  logic activation_stream_valid,
    output logic activation_stream_ready,
    input  logic [63:0] activation_stream_values,
    input  logic [7:0] activation_stream_lane_mask,
    input  logic activation_stream_last,

    input  logic result_dma_clear_error,
    input  logic result_dma_descriptor_valid,
    output logic result_dma_descriptor_ready,
    input  logic [BANK_COUNT_W-1:0] result_dma_descriptor_word_count,
    input  logic [DMA_BYTE_COUNT_W-1:0]
        result_dma_descriptor_byte_count,
    input  logic [1:0] result_dma_descriptor_destination,
    input  logic [2:0] result_dma_descriptor_slice,
    input  logic [N_BASE_W-1:0] result_dma_descriptor_n_base,
    input  logic [7:0] result_dma_descriptor_lane_mask,
    input  logic [TILE_TAG_W-1:0]
        result_dma_descriptor_first_tile_tag,
    output logic [127:0] m_axis_tdata,
    output logic [15:0] m_axis_tkeep,
    output logic m_axis_tvalid,
    input  logic m_axis_tready,
    output logic m_axis_tlast,

    input  logic weight_release_valid,
    output logic weight_release_ready,

    input  logic chunk_valid,
    output logic chunk_ready,
    input  logic chunk_activation_streaming,
    input  logic [TENSOR_TAG_W-1:0] chunk_activation_tensor_tag,
    input  logic [DIM_W-1:0] chunk_input_h,
    input  logic [DIM_W-1:0] chunk_input_w,
    input  logic [3:0] chunk_channel_count,
    input  logic [7:0] chunk_input_lane_mask,
    input  logic [3:0] chunk_kernel,
    input  logic [2:0] chunk_stride,
    input  logic [2:0] chunk_padding,
    input  logic [WEIGHT_COUNT_W-1:0] chunk_k_count,
    input  logic [WEIGHT_CONTEXT_TAG_W-1:0]
        chunk_weight_context_tag,
    input  logic [BANK_COUNT_W-1:0] chunk_word_count,
    input  logic [DIM_W-1:0] chunk_output_width,
    input  logic [ACCUM_CONTEXT_TAG_W-1:0] chunk_accum_context_tag,
    input  logic [TILE_TAG_W-1:0] chunk_tile_tag_base,
    input  logic [CHUNK_INDEX_W-1:0] chunk_index,
    input  logic chunk_first,
    input  logic chunk_final,

    output logic configured,
    output logic chunk_frame_active,
    output logic chunk_done,
    output logic chunk_rejected,
    output logic compute_busy,
    output logic transaction_active,
    output logic accum_chunk_active,
    output logic transaction_done,
    output logic pipeline_idle,
    output logic protocol_error,
    output logic activation_context_error,
    output logic accum_context_error,
    output logic weight_context_error,
    output logic [15:0] completed_tile_count,
    output logic [15:0] completed_weight_replays,
    output logic [1:0] weight_bank_state,
    output logic weight_resident_valid,
    output logic [WEIGHT_COUNT_W-1:0] resident_weight_k_count,
    output logic [WEIGHT_COUNT_W-1:0] resident_weight_words_written,
    output logic [7:0] resident_weight_n_lane_mask,
    output logic [WEIGHT_CONTEXT_TAG_W-1:0]
        resident_weight_context_tag,
    output logic weight_replay_done,
    output logic [2:0] accum_bank_state,
    output logic [$clog2(FIFO_DEPTH+1)-1:0] queued_count,

    output logic activation_ready_tensor_valid,
    output logic activation_ready_tensor_bank,
    output logic [TENSOR_TAG_W-1:0] activation_ready_tensor_tag,
    output logic [1:0] activation_ready_count,
    output logic activation_fill_active,
    output logic activation_fill_bank,
    output logic activation_read_active,
    output logic activation_read_bank,
    output logic activation_read_segment,
    output logic activation_read_done,
    output logic [ACTIVATION_COUNT_W-1:0] activation_words_forwarded,
    output logic [15:0] activation_stream_words_forwarded,

    output logic dma_busy,
    output logic dma_transfer_active,
    output logic dma_transfer_done,
    output logic dma_descriptor_rejected,
    output logic dma_descriptor_error,
    output logic dma_stream_error,
    output logic dma_protocol_error,
    output logic [1:0] dma_active_destination,
    output logic [ACTIVATION_COUNT_W-1:0] dma_words_transferred,
    output logic [15:0] dma_completed_transfers,

    output logic result_dma_busy,
    output logic result_dma_transfer_active,
    output logic result_dma_transfer_done,
    output logic result_dma_descriptor_rejected,
    output logic result_dma_descriptor_error,
    output logic result_dma_metadata_error,
    output logic result_dma_protocol_error,
    output logic [1:0] result_dma_active_destination,
    output logic [2:0] result_dma_active_slice,
    output logic [N_BASE_W-1:0] result_dma_active_n_base,
    output logic [7:0] result_dma_active_lane_mask,
    output logic [TILE_TAG_W-1:0] result_dma_active_first_tile_tag,
    output logic [BANK_COUNT_W-1:0] result_dma_words_accepted,
    output logic [BANK_COUNT_W-1:0] result_dma_words_transferred,
    output logic [BANK_COUNT_W-1:0] result_dma_beats_transferred,
    output logic [15:0] result_dma_completed_transfers,
    output logic [TILE_TAG_W-1:0]
        result_dma_completed_first_tile_tag,
    output logic [TILE_TAG_W-1:0]
        result_dma_completed_last_tile_tag,

    // Optional shared compute link; ignored by the default local implementation.
    output logic shared_cfg_valid,
    input logic shared_cfg_ready,
    output logic [1:0] shared_cfg_destination,
    output logic [15:0] shared_cfg_n64_tile_base,
    output logic [2:0] shared_cfg_slice_index,
    output logic [7:0] shared_cfg_lane_mask,
    output logic signed [31:0] shared_cfg_bias [0:7],
    output logic signed [17:0] shared_cfg_multiplier [0:7],
    output logic [5:0] shared_cfg_right_shift [0:7],
    output logic [7:0] shared_cfg_relu,
    output logic shared_chunk_valid,
    input logic shared_chunk_ready,
    output logic [12:0] shared_chunk_word_count,
    output logic [7:0] shared_chunk_output_width,
    output logic [7:0] shared_chunk_n_lane_mask,
    output logic [15:0] shared_chunk_context_tag,
    output logic [15:0] shared_chunk_tile_tag_base,
    output logic [7:0] shared_chunk_index,
    output logic shared_chunk_first,
    output logic shared_chunk_final,
    output logic shared_tile_start_valid,
    input logic shared_tile_start_ready,
    output logic [2:0] shared_tile_m_count,
    output logic [7:0] shared_tile_n_lane_mask,
    output logic [15:0] shared_tile_tag,
    output logic shared_issue_valid,
    input logic shared_issue_ready,
    output logic shared_issue_last,
    output logic signed [7:0] shared_issue_act_lo [0:1],
    output logic signed [7:0] shared_issue_act_hi [0:1],
    output logic signed [7:0] shared_issue_weight [0:7],
    input logic shared_egress_valid,
    output logic shared_egress_ready,
    input logic [63:0] shared_egress_values,
    input logic [7:0] shared_egress_lane_mask,
    input logic [1:0] shared_egress_destination,
    input logic [2:0] shared_egress_slice,
    input logic [4:0] shared_egress_m,
    input logic [15:0] shared_egress_n_base,
    input logic [15:0] shared_egress_tile_tag,
    input logic shared_configured,
    input logic shared_compute_busy,
    input logic shared_transaction_active,
    input logic shared_chunk_active,
    input logic shared_tile_done,
    input logic shared_chunk_done,
    input logic shared_transaction_done,
    input logic shared_datapath_idle,
    input logic [2:0] shared_accum_bank_state,
    input logic shared_accum_context_error,
    input logic shared_protocol_error,
    input logic [6:0] shared_queued_count
);

  logic core_chunk_valid;
  logic core_chunk_ready;
  logic core_pipeline_idle;
  logic core_protocol_error;
  logic core_egress_valid;
  logic core_egress_ready;
  logic [63:0] core_egress_values;
  logic [7:0] core_egress_lane_mask;
  logic [1:0] core_egress_destination;
  logic [2:0] core_egress_slice;
  logic [4:0] core_egress_m;
  logic [N_BASE_W-1:0] core_egress_n_base;
  logic [TILE_TAG_W-1:0] core_egress_tile_tag;

  assign core_chunk_valid = chunk_valid && !result_dma_protocol_error;
  assign chunk_ready = core_chunk_ready && !result_dma_protocol_error;
  assign pipeline_idle = core_pipeline_idle && !result_dma_busy;
  assign protocol_error = core_protocol_error || result_dma_protocol_error;

  alexnet_m4n8_rs_dma_activation_resident_weight_dual_accum_datapath #(
      .EXTERNAL_COMPUTE(EXTERNAL_COMPUTE),
      .SLICE_INDEX(SLICE_INDEX),
      .FIFO_DEPTH(FIFO_DEPTH),
      .MAX_INPUT_WIDTH(MAX_INPUT_WIDTH),
      .WEIGHT_DEPTH(WEIGHT_DEPTH),
      .SEGMENT_DEPTH(SEGMENT_DEPTH),
      .DIM_W(DIM_W),
      .K_INDEX_W(K_INDEX_W),
      .TILE_TAG_W(TILE_TAG_W),
      .TENSOR_TAG_W(TENSOR_TAG_W),
      .WEIGHT_CONTEXT_TAG_W(WEIGHT_CONTEXT_TAG_W),
      .ACCUM_CONTEXT_TAG_W(ACCUM_CONTEXT_TAG_W),
      .CHUNK_INDEX_W(CHUNK_INDEX_W),
      .N_BASE_W(N_BASE_W),
      .DMA_BYTE_COUNT_W(DMA_BYTE_COUNT_W),
      .WEIGHT_COUNT_W(WEIGHT_COUNT_W),
      .ACTIVATION_COUNT_W(ACTIVATION_COUNT_W),
      .BANK_COUNT_W(BANK_COUNT_W)
  ) u_dma_fed_datapath (
      .shared_cfg_valid(shared_cfg_valid),
      .shared_cfg_ready(shared_cfg_ready),
      .shared_cfg_destination(shared_cfg_destination),
      .shared_cfg_n64_tile_base(shared_cfg_n64_tile_base),
      .shared_cfg_slice_index(shared_cfg_slice_index),
      .shared_cfg_lane_mask(shared_cfg_lane_mask),
      .shared_cfg_bias(shared_cfg_bias),
      .shared_cfg_multiplier(shared_cfg_multiplier),
      .shared_cfg_right_shift(shared_cfg_right_shift),
      .shared_cfg_relu(shared_cfg_relu),
      .shared_chunk_valid(shared_chunk_valid),
      .shared_chunk_ready(shared_chunk_ready),
      .shared_chunk_word_count(shared_chunk_word_count),
      .shared_chunk_output_width(shared_chunk_output_width),
      .shared_chunk_n_lane_mask(shared_chunk_n_lane_mask),
      .shared_chunk_context_tag(shared_chunk_context_tag),
      .shared_chunk_tile_tag_base(shared_chunk_tile_tag_base),
      .shared_chunk_index(shared_chunk_index),
      .shared_chunk_first(shared_chunk_first),
      .shared_chunk_final(shared_chunk_final),
      .shared_tile_start_valid(shared_tile_start_valid),
      .shared_tile_start_ready(shared_tile_start_ready),
      .shared_tile_m_count(shared_tile_m_count),
      .shared_tile_n_lane_mask(shared_tile_n_lane_mask),
      .shared_tile_tag(shared_tile_tag),
      .shared_issue_valid(shared_issue_valid),
      .shared_issue_ready(shared_issue_ready),
      .shared_issue_last(shared_issue_last),
      .shared_issue_act_lo(shared_issue_act_lo),
      .shared_issue_act_hi(shared_issue_act_hi),
      .shared_issue_weight(shared_issue_weight),
      .shared_egress_valid(shared_egress_valid),
      .shared_egress_ready(shared_egress_ready),
      .shared_egress_values(shared_egress_values),
      .shared_egress_lane_mask(shared_egress_lane_mask),
      .shared_egress_destination(shared_egress_destination),
      .shared_egress_slice(shared_egress_slice),
      .shared_egress_m(shared_egress_m),
      .shared_egress_n_base(shared_egress_n_base),
      .shared_egress_tile_tag(shared_egress_tile_tag),
      .shared_configured(shared_configured),
      .shared_compute_busy(shared_compute_busy),
      .shared_transaction_active(shared_transaction_active),
      .shared_chunk_active(shared_chunk_active),
      .shared_tile_done(shared_tile_done),
      .shared_chunk_done(shared_chunk_done),
      .shared_transaction_done(shared_transaction_done),
      .shared_datapath_idle(shared_datapath_idle),
      .shared_accum_bank_state(shared_accum_bank_state),
      .shared_accum_context_error(shared_accum_context_error),
      .shared_protocol_error(shared_protocol_error),
      .shared_queued_count(shared_queued_count),
      .clk(clk),
      .rst(rst),
      .ce(ce),
      .cfg_valid(cfg_valid),
      .cfg_ready(cfg_ready),
      .cfg_destination(cfg_destination),
      .cfg_n64_tile_base(cfg_n64_tile_base),
      .cfg_slice_index(cfg_slice_index),
      .cfg_lane_mask(cfg_lane_mask),
      .cfg_bias(cfg_bias),
      .cfg_multiplier(cfg_multiplier),
      .cfg_right_shift(cfg_right_shift),
      .cfg_relu(cfg_relu),
      .dma_clear_error(dma_clear_error),
      .dma_descriptor_valid(dma_descriptor_valid),
      .dma_descriptor_ready(dma_descriptor_ready),
      .dma_descriptor_destination(dma_descriptor_destination),
      .dma_descriptor_word_count(dma_descriptor_word_count),
      .dma_descriptor_byte_count(dma_descriptor_byte_count),
      .dma_descriptor_lane_mask(dma_descriptor_lane_mask),
      .dma_descriptor_tag(dma_descriptor_tag),
      .s_axis_tdata(s_axis_tdata),
      .s_axis_tkeep(s_axis_tkeep),
      .s_axis_tvalid(s_axis_tvalid),
      .s_axis_tready(s_axis_tready),
      .s_axis_tlast(s_axis_tlast),
      .activation_stream_valid(activation_stream_valid),
      .activation_stream_ready(activation_stream_ready),
      .activation_stream_values(activation_stream_values),
      .activation_stream_lane_mask(activation_stream_lane_mask),
      .activation_stream_last(activation_stream_last),
      .weight_release_valid(weight_release_valid),
      .weight_release_ready(weight_release_ready),
      .chunk_valid(core_chunk_valid),
      .chunk_ready(core_chunk_ready),
      .chunk_activation_streaming(chunk_activation_streaming),
      .chunk_activation_tensor_tag(chunk_activation_tensor_tag),
      .chunk_input_h(chunk_input_h),
      .chunk_input_w(chunk_input_w),
      .chunk_channel_count(chunk_channel_count),
      .chunk_input_lane_mask(chunk_input_lane_mask),
      .chunk_kernel(chunk_kernel),
      .chunk_stride(chunk_stride),
      .chunk_padding(chunk_padding),
      .chunk_k_count(chunk_k_count),
      .chunk_weight_context_tag(chunk_weight_context_tag),
      .chunk_word_count(chunk_word_count),
      .chunk_output_width(chunk_output_width),
      .chunk_accum_context_tag(chunk_accum_context_tag),
      .chunk_tile_tag_base(chunk_tile_tag_base),
      .chunk_index(chunk_index),
      .chunk_first(chunk_first),
      .chunk_final(chunk_final),
      .egress_valid(core_egress_valid),
      .egress_ready(core_egress_ready),
      .egress_values(core_egress_values),
      .egress_lane_mask(core_egress_lane_mask),
      .egress_destination(core_egress_destination),
      .egress_slice(core_egress_slice),
      .egress_m(core_egress_m),
      .egress_n_base(core_egress_n_base),
      .egress_tile_tag(core_egress_tile_tag),
      .configured(configured),
      .chunk_frame_active(chunk_frame_active),
      .chunk_done(chunk_done),
      .chunk_rejected(chunk_rejected),
      .compute_busy(compute_busy),
      .transaction_active(transaction_active),
      .accum_chunk_active(accum_chunk_active),
      .transaction_done(transaction_done),
      .pipeline_idle(core_pipeline_idle),
      .protocol_error(core_protocol_error),
      .activation_context_error(activation_context_error),
      .accum_context_error(accum_context_error),
      .weight_context_error(weight_context_error),
      .completed_tile_count(completed_tile_count),
      .completed_weight_replays(completed_weight_replays),
      .weight_bank_state(weight_bank_state),
      .weight_resident_valid(weight_resident_valid),
      .resident_weight_k_count(resident_weight_k_count),
      .resident_weight_words_written(resident_weight_words_written),
      .resident_weight_n_lane_mask(resident_weight_n_lane_mask),
      .resident_weight_context_tag(resident_weight_context_tag),
      .weight_replay_done(weight_replay_done),
      .accum_bank_state(accum_bank_state),
      .queued_count(queued_count),
      .activation_ready_tensor_valid(activation_ready_tensor_valid),
      .activation_ready_tensor_bank(activation_ready_tensor_bank),
      .activation_ready_tensor_tag(activation_ready_tensor_tag),
      .activation_ready_count(activation_ready_count),
      .activation_fill_active(activation_fill_active),
      .activation_fill_bank(activation_fill_bank),
      .activation_read_active(activation_read_active),
      .activation_read_bank(activation_read_bank),
      .activation_read_segment(activation_read_segment),
      .activation_read_done(activation_read_done),
      .activation_words_forwarded(activation_words_forwarded),
      .activation_stream_words_forwarded(
          activation_stream_words_forwarded),
      .dma_busy(dma_busy),
      .dma_transfer_active(dma_transfer_active),
      .dma_transfer_done(dma_transfer_done),
      .dma_descriptor_rejected(dma_descriptor_rejected),
      .dma_descriptor_error(dma_descriptor_error),
      .dma_stream_error(dma_stream_error),
      .dma_protocol_error(dma_protocol_error),
      .dma_active_destination(dma_active_destination),
      .dma_words_transferred(dma_words_transferred),
      .dma_completed_transfers(dma_completed_transfers)
  );

  alexnet_n8_dma_result_egress #(
      .COUNT_W(BANK_COUNT_W),
      .BYTE_COUNT_W(DMA_BYTE_COUNT_W),
      .N_BASE_W(N_BASE_W),
      .TILE_TAG_W(TILE_TAG_W),
      .MAX_WORDS(RESULT_MAX_WORDS)
  ) u_result_dma_egress (
      .clk(clk),
      .rst(rst),
      .clear_error(result_dma_clear_error),
      .descriptor_valid(result_dma_descriptor_valid),
      .descriptor_ready(result_dma_descriptor_ready),
      .descriptor_word_count(result_dma_descriptor_word_count),
      .descriptor_byte_count(result_dma_descriptor_byte_count),
      .descriptor_destination(result_dma_descriptor_destination),
      .descriptor_slice(result_dma_descriptor_slice),
      .descriptor_n_base(result_dma_descriptor_n_base),
      .descriptor_lane_mask(result_dma_descriptor_lane_mask),
      .descriptor_first_tile_tag(result_dma_descriptor_first_tile_tag),
      .packet_valid(core_egress_valid),
      .packet_ready(core_egress_ready),
      .packet_values(core_egress_values),
      .packet_lane_mask(core_egress_lane_mask),
      .packet_destination(core_egress_destination),
      .packet_slice(core_egress_slice),
      .packet_m(core_egress_m),
      .packet_n_base(core_egress_n_base),
      .packet_tile_tag(core_egress_tile_tag),
      .m_axis_tdata(m_axis_tdata),
      .m_axis_tkeep(m_axis_tkeep),
      .m_axis_tvalid(m_axis_tvalid),
      .m_axis_tready(m_axis_tready),
      .m_axis_tlast(m_axis_tlast),
      .busy(result_dma_busy),
      .transfer_active(result_dma_transfer_active),
      .transfer_done(result_dma_transfer_done),
      .descriptor_rejected(result_dma_descriptor_rejected),
      .descriptor_error(result_dma_descriptor_error),
      .metadata_error(result_dma_metadata_error),
      .protocol_error(result_dma_protocol_error),
      .active_destination(result_dma_active_destination),
      .active_slice(result_dma_active_slice),
      .active_n_base(result_dma_active_n_base),
      .active_lane_mask(result_dma_active_lane_mask),
      .active_first_tile_tag(result_dma_active_first_tile_tag),
      .words_accepted(result_dma_words_accepted),
      .words_transferred(result_dma_words_transferred),
      .beats_transferred(result_dma_beats_transferred),
      .completed_transfers(result_dma_completed_transfers),
      .completed_first_tile_tag(result_dma_completed_first_tile_tag),
      .completed_last_tile_tag(result_dma_completed_last_tile_tag)
  );

`ifndef SYNTHESIS
  always_ff @(posedge clk) begin
    if (!rst) begin
      if (result_dma_protocol_error && core_chunk_valid)
        $fatal(1, "result DMA error failed to interlock next chunk");
      if (core_egress_valid && core_egress_ready &&
          !result_dma_transfer_active)
        $fatal(1, "result packet was consumed without an S2MM descriptor");
      if (result_dma_descriptor_rejected && core_egress_ready)
        $fatal(1, "rejected result descriptor consumed router payload");
    end
  end
`endif

endmodule
