`timescale 1ns/1ps
module tb_alexnet_row_stationary_control;
 localparam CTRL_ADDR_W=8;
 logic aclk;
 logic aresetn;
 logic [CTRL_ADDR_W-1:0] s_axi_ctrl_awaddr;
 logic [2:0] s_axi_ctrl_awprot;
 logic s_axi_ctrl_awvalid;
 logic s_axi_ctrl_awready;
 logic [31:0] s_axi_ctrl_wdata;
 logic [3:0] s_axi_ctrl_wstrb;
 logic s_axi_ctrl_wvalid;
 logic s_axi_ctrl_wready;
 logic [1:0] s_axi_ctrl_bresp;
 logic s_axi_ctrl_bvalid;
 logic s_axi_ctrl_bready;
 logic [CTRL_ADDR_W-1:0] s_axi_ctrl_araddr;
 logic [2:0] s_axi_ctrl_arprot;
 logic s_axi_ctrl_arvalid;
 logic s_axi_ctrl_arready;
 logic [31:0] s_axi_ctrl_rdata;
 logic [1:0] s_axi_ctrl_rresp;
 logic s_axi_ctrl_rvalid;
 logic s_axi_ctrl_rready;
 logic [63:0] s_axis_camera_tdata;
 logic [7:0] s_axis_camera_tkeep;
 logic s_axis_camera_tvalid;
 logic s_axis_camera_tready;
 logic s_axis_camera_tlast;
 logic [127:0] s_axis_mm2s_tdata;
 logic [15:0] s_axis_mm2s_tkeep;
 logic s_axis_mm2s_tvalid;
 logic s_axis_mm2s_tready;
 logic s_axis_mm2s_tlast;
 logic [127:0] s_axis_weight_tdata;
 logic [15:0] s_axis_weight_tkeep;
 logic s_axis_weight_tvalid;
 logic s_axis_weight_tready;
 logic s_axis_weight_tlast;
 logic [127:0] m_axis_s2mm_tdata;
 logic [15:0] m_axis_s2mm_tkeep;
 logic m_axis_s2mm_tvalid;
 logic m_axis_s2mm_tready;
 logic m_axis_s2mm_tlast;
 logic [31:0] m_axi_dma_awaddr;
 logic [2:0] m_axi_dma_awprot;
 logic m_axi_dma_awvalid;
 logic m_axi_dma_awready;
 logic [31:0] m_axi_dma_wdata;
 logic [3:0] m_axi_dma_wstrb;
 logic m_axi_dma_wvalid;
 logic m_axi_dma_wready;
 logic [1:0] m_axi_dma_bresp;
 logic m_axi_dma_bvalid;
 logic m_axi_dma_bready;
 logic [31:0] m_axi_dma_araddr;
 logic [2:0] m_axi_dma_arprot;
 logic m_axi_dma_arvalid;
 logic m_axi_dma_arready;
 logic [31:0] m_axi_dma_rdata;
 logic [1:0] m_axi_dma_rresp;
 logic m_axi_dma_rvalid;
 logic m_axi_dma_rready;
 logic [31:0] m_axi_weight_dma_awaddr;
 logic [2:0] m_axi_weight_dma_awprot;
 logic m_axi_weight_dma_awvalid;
 logic m_axi_weight_dma_awready;
 logic [31:0] m_axi_weight_dma_wdata;
 logic [3:0] m_axi_weight_dma_wstrb;
 logic m_axi_weight_dma_wvalid;
 logic m_axi_weight_dma_wready;
 logic [1:0] m_axi_weight_dma_bresp;
 logic m_axi_weight_dma_bvalid;
 logic m_axi_weight_dma_bready;
 logic [31:0] m_axi_weight_dma_araddr;
 logic [2:0] m_axi_weight_dma_arprot;
 logic m_axi_weight_dma_arvalid;
 logic m_axi_weight_dma_arready;
 logic [31:0] m_axi_weight_dma_rdata;
 logic [1:0] m_axi_weight_dma_rresp;
 logic m_axi_weight_dma_rvalid;
 logic m_axi_weight_dma_rready;
 logic irq;
 logic accelerator_busy;
 logic accelerator_fault;
 alexnet_row_stationary_accelerator_top dut(.*);
 always #2.5 aclk=~aclk;
 task automatic wr(input integer address,input logic[31:0] value);
   @(negedge aclk);s_axi_ctrl_awaddr=8'(address);s_axi_ctrl_awvalid=1;
   do @(posedge aclk);while(!s_axi_ctrl_awready);
   @(negedge aclk);s_axi_ctrl_awvalid=0;
   repeat(2) @(negedge aclk);s_axi_ctrl_wdata=value;s_axi_ctrl_wvalid=1;
   do @(posedge aclk);while(!s_axi_ctrl_wready);
   @(negedge aclk);s_axi_ctrl_wvalid=0;s_axi_ctrl_bready=1;
   do @(posedge aclk);while(!s_axi_ctrl_bvalid);
   if(s_axi_ctrl_bresp!=0) $fatal(1,"write response");
   @(negedge aclk);s_axi_ctrl_bready=0;
 endtask
 task automatic rd(input integer address,input logic[31:0] expected,input logic[1:0] response=0);
   logic[31:0] held;logic[1:0] held_resp;
   @(negedge aclk);s_axi_ctrl_araddr=8'(address);s_axi_ctrl_arvalid=1;s_axi_ctrl_rready=0;
   do @(posedge aclk);while(!s_axi_ctrl_arready);
   @(negedge aclk);s_axi_ctrl_arvalid=0;
   wait(s_axi_ctrl_rvalid);held=s_axi_ctrl_rdata;held_resp=s_axi_ctrl_rresp;
   repeat(5) begin
     @(negedge aclk);
     if(!s_axi_ctrl_rvalid || s_axi_ctrl_rdata!==held || s_axi_ctrl_rresp!==held_resp) $fatal(1,"stalled CSR response changed");
   end
   if(held!==expected || held_resp!==response) $fatal(1,"CSR %h got=%h expected=%h response=%d",address,held,expected,held_resp);
   s_axi_ctrl_rready=1;@(posedge aclk);@(negedge aclk);s_axi_ctrl_rready=0;
 endtask
 initial begin
   aclk=0;aresetn=0;s_axi_ctrl_awvalid=0;s_axi_ctrl_wvalid=0;s_axi_ctrl_bready=0;
   s_axi_ctrl_arvalid=0;s_axi_ctrl_rready=0;s_axi_ctrl_awaddr=0;s_axi_ctrl_araddr=0;s_axi_ctrl_wdata=0;s_axi_ctrl_wstrb=15;
   s_axi_ctrl_awprot=0;s_axi_ctrl_arprot=0;
   s_axis_camera_tdata=0;s_axis_camera_tkeep=0;s_axis_camera_tvalid=0;s_axis_camera_tlast=0;
   s_axis_mm2s_tdata=0;s_axis_mm2s_tkeep=0;s_axis_mm2s_tvalid=0;s_axis_mm2s_tlast=0;
   s_axis_weight_tdata=0;s_axis_weight_tkeep=0;s_axis_weight_tvalid=0;s_axis_weight_tlast=0;m_axis_s2mm_tready=0;
   m_axi_dma_awready=0;m_axi_dma_wready=0;m_axi_dma_bresp=0;m_axi_dma_bvalid=0;m_axi_dma_arready=0;m_axi_dma_rdata=0;m_axi_dma_rresp=0;m_axi_dma_rvalid=0;
   m_axi_weight_dma_awready=0;m_axi_weight_dma_wready=0;m_axi_weight_dma_bresp=0;m_axi_weight_dma_bvalid=0;m_axi_weight_dma_arready=0;m_axi_weight_dma_rdata=0;m_axi_weight_dma_rresp=0;m_axi_weight_dma_rvalid=0;
   repeat(6) @(negedge aclk);aresetn=1;
   // Isolate control/telemetry from computation; the real core and DMA paths
   // are exercised by the separate trained-core and DDR engine regressions.
   force dut.core_start_ready=1'b1;force dut.engine_busy=1'b0;force dut.engine_done=1'b0;force dut.engine_fault=1'b0;
   force dut.main_read_axis_bytes=64'd100;force dut.main_write_axis_bytes=64'd50;
   force dut.weight_service_bytes=64'd1000;force dut.gather_requested_bytes=64'd80;
   force dut.useful_mac_count=64'd500;force dut.stored_packets=32'd5;
   force dut.main_completed_transfers=32'd9;force dut.completed_commands=32'd0;force dut.completed_input_tiles=32'd0;
   rd('h00,32'h52530100);rd('h7c,32'h088000c8);rd('hb0,100);rd('hec,0,2'b10);rd('hb1,0,2'b10);
   for(int a='h10;a<='h38;a+=8) begin wr(a,32'h00100000+32'(a)*128);wr(a+4,0);end
   wr('h0c,1);wr('h04,1);repeat(5) @(negedge aclk);
   force dut.main_read_axis_bytes=64'd1100;force dut.main_write_axis_bytes=64'd650;
   force dut.weight_service_bytes=64'd5000;force dut.gather_requested_bytes=64'd880;
   force dut.useful_mac_count=64'd714188980;force dut.stored_packets=32'd25;
   force dut.main_completed_transfers=32'd49;force dut.completed_commands=32'd56104;force dut.completed_input_tiles=32'd1305;
   force dut.engine_done=1'b1;@(negedge aclk);force dut.engine_done=1'b0;
   rd('hb0,1000);rd('hb8,600);rd('hc0,4000);rd('hc8,800);rd('hd0,20);rd('hd4,56104);rd('he8,1305);rd('he0,5600);rd('h94,714188480);
   wr('h04,2);wr('h0c,2);wr('h04,1);repeat(5) @(negedge aclk);
   force dut.main_read_axis_bytes=64'h1_000007dc;force dut.main_write_axis_bytes=64'd1250;
   force dut.weight_service_bytes=64'd9000;force dut.gather_requested_bytes=64'd1680;
   force dut.useful_mac_count=64'd1428377460;force dut.stored_packets=32'd45;
   force dut.main_completed_transfers=32'd89;force dut.completed_commands=32'd56104;force dut.completed_input_tiles=32'd1305;
   force dut.engine_done=1'b1;@(negedge aclk);force dut.engine_done=1'b0;
   rd('hb0,912);rd('hb4,1);rd('hb8,600);rd('hc0,4000);rd('hd0,20);rd('hd4,56104);rd('he8,1305);rd('h94,714188480);
   $display("ALEXNET_ROW_STATIONARY_CONTROL_TEST_PASSED jobs=2 telemetry_backpressure=1");$finish;
 end
 initial begin #1000000;$fatal(1,"control timeout");end
endmodule
